[ImGui]
url = "https://github.com/roguemacro/imgui-beef-2"
description = "Dear ImGui wrapper for Beef"

[ImGui.versions."1.88.0"]
rev = "caa69bc1175567923547377590f0aebf0b01cad5"

  [ImGui.versions."1.88.0".deps]
  GLFW = "*"

[GLFW]
url = "https://github.com/RogueMacro/glfw-beef"
description = "Beef wrapper library for GLFW 3.3.4"

[GLFW.versions."3.3.4"]
rev = "cc1f74d69b5b0760dc4e42f84a448ee1f5516467"
deps = { }

[OpenGL]
url = "https://github.com/RogueMacro/opengl-beef.git"
description = "OpenGL bindings"

[OpenGL.versions."3.3.0"]
rev = "3551cdc9cb576534d4e3a2efb3f3eabce565f9f7"
deps = { }

[BuildTools]
url = "https://github.com/roguemacro/grill-buildtools"
description = "Build tools for Grill packages"

[BuildTools.versions."0.1.0"]
rev = "a403e1d34eabfba77d269b8f5a9e98941d33b3b0"
deps = { }

[BuildTools.versions."0.2.0"]
rev = "d9acea8369695b2b7b76c7d2384116d505eaf541"
deps = { }

[dummy]
url = "https://github.com/roguemacro/dummy"
description = ""

[dummy.versions."0.1.0"]
rev = "9aef26a47ae2b5d68809d694088c5fc66ec5744e"
deps = { }
