[ImGui]
url = "https://github.com/roguemacro/imgui-beef-2"
description = "Dear ImGui wrapper for Beef"

[ImGui.versions."1.88.0"]
rev = "caa69bc1175567923547377590f0aebf0b01cad5"

  [ImGui.versions."1.88.0".deps]
  GLFW = "*"

[ImGui.versions."1.88.1"]
rev = "d0339553b3f85c1c157de19b5fa6c7ad57bd50bd"

  [ImGui.versions."1.88.1".deps]
  GLFW = "*"
  SDL2 = "*"

[OpenGL]
url = "https://github.com/RogueMacro/opengl-beef.git"
description = "OpenGL bindings"

[OpenGL.versions."3.3.0"]
rev = "3551cdc9cb576534d4e3a2efb3f3eabce565f9f7"
deps = { }

[BuildTools]
url = "https://github.com/roguemacro/grill-buildtools"
description = "Build tools for Grill packages"

[BuildTools.versions."0.1.0"]
rev = "a403e1d34eabfba77d269b8f5a9e98941d33b3b0"
deps = { }

[BuildTools.versions."0.2.0"]
rev = "d9acea8369695b2b7b76c7d2384116d505eaf541"
deps = { }

[BuildTools.versions."0.2.1"]
rev = "a08a878b07f48445bf3eedbb61b383d66022dd1d"
deps = { }

[BuildTools.versions."0.2.2"]
rev = "bb1eb6dc87bef38b28a848cf141053a3775bdb20"
deps = { }

[dummy]
url = "https://github.com/roguemacro/dummy"
description = ""

[dummy.versions."0.1.0"]
rev = "9aef26a47ae2b5d68809d694088c5fc66ec5744e"
deps = { }

[GLFW]
url = "https://github.com/MineGame159/glfw-beef.git"
description = "Beef wrapper library for GLFW 3.3.4"

[GLFW.versions."3.3.4"]
rev = "b4f19bfe07af2af24811351935a20aba1fcac811"
deps = { }

[SDL2]
url = "https://github.com/RogueMacro/SDL2-beef.git"
description = "SDL2 wrapper for Beef"

[SDL2.versions."0.1.0"]
rev = "391ce43979dd18f48f84d596ae401484df9dffdb"
deps = { }

[SDL2.versions."0.1.1"]
rev = "3c19bab83cb3ab7507e9d79bcc54f9e8dbdbc35b"
deps = { }

[TailTrace]
url = "https://github.com/RogueMacro/TailTrace.git"
description = "Logging and console style utilities"

[TailTrace.versions."0.1.0"]
rev = "f3721e2e0bc64c596d24789a1ac50d7ef1771978"
deps = { }

[TailTrace.versions."0.1.1"]
rev = "a6aed0ab84d00fed287be30fc8200390239fae2b"
deps = { }

[Serialize]
url = "https://github.com/RogueMacro/serialize.git"
description = "De-/serialization framework"

[Serialize.versions."0.1.0"]
rev = "4765f666529cea0eba7f0754a8b6bcdff41151d1"
deps = { }

[Json]
url = "https://github.com/RogueMacro/json.git"
description = "JSON serialization format"

[Json.versions."0.1.0"]
rev = "8f3d52755eb92cd020aa85beadf86f3ac0819847"

  [Json.versions."0.1.0".deps]
  Serialize = "^0.1.0"

[Toml]
url = "https://github.com/RogueMacro/toml.git"
description = "TOML serialization format"

[Toml.versions."0.1.0"]
rev = "e23bc14337ba87eaaf0e04973fe442e20cf88d1c"

  [Toml.versions."0.1.0".deps]
  Serialize = "^0.1.0"
