[ImGui]
url = "https://github.com/roguemacro/imgui-beef"
description = "Dear ImGui wrapper for Beef"

[ImGui.versions."1.88.0"]
rev = "32093514f47b28c4df945f0a3284bd49eaf7e144"

  [ImGui.versions."1.88.0".deps]
  GLFW = "*"

[GLFW]
url = "https://github.com/RogueMacro/glfw-beef"
description = "Beef wrapper library for GLFW 3.3.4"

[GLFW.versions."3.3.4"]
rev = "cc1f74d69b5b0760dc4e42f84a448ee1f5516467"
deps = { }

[OpenGL]
url = "https://github.com/RogueMacro/opengl-beef.git"
description = "OpenGL bindings"

[OpenGL.versions."3.3.0"]
rev = "3551cdc9cb576534d4e3a2efb3f3eabce565f9f7"
deps = { }

[BuildTools]
url = "https://github.com/roguemacro/grill-buildtools"
description = "Build tools for Grill packages"

[BuildTools.versions."0.1.0"]
rev = "a403e1d34eabfba77d269b8f5a9e98941d33b3b0"
deps = { }
