[ImGui]
url = "https://github.com/roguemacro/imgui-beef-2"
description = "Dear ImGui wrapper for Beef"

[ImGui.versions."1.88.0"]
rev = "caa69bc1175567923547377590f0aebf0b01cad5"

  [ImGui.versions."1.88.0".deps]
  GLFW = "*"

[ImGui.versions."1.88.1"]
rev = "9d0d3cde01e23e66075cd0b7110425781264499b"

  [ImGui.versions."1.88.1".deps]
  GLFW = "*"
  SDL2 = "*"

[OpenGL]
url = "https://github.com/RogueMacro/opengl-beef.git"
description = "OpenGL bindings"

[OpenGL.versions."3.3.0"]
rev = "3551cdc9cb576534d4e3a2efb3f3eabce565f9f7"
deps = { }

[BuildTools]
url = "https://github.com/roguemacro/grill-buildtools"
description = "Build tools for Grill packages"

[BuildTools.versions."0.1.0"]
rev = "a403e1d34eabfba77d269b8f5a9e98941d33b3b0"
deps = { }

[BuildTools.versions."0.2.0"]
rev = "d9acea8369695b2b7b76c7d2384116d505eaf541"
deps = { }

[BuildTools.versions."0.2.1"]
rev = "a08a878b07f48445bf3eedbb61b383d66022dd1d"
deps = { }

[dummy]
url = "https://github.com/roguemacro/dummy"
description = ""

[dummy.versions."0.1.0"]
rev = "9aef26a47ae2b5d68809d694088c5fc66ec5744e"
deps = { }

[GLFW]
url = "https://github.com/MineGame159/glfw-beef.git"
description = "Beef wrapper library for GLFW 3.3.4"

[GLFW.versions."3.3.4"]
rev = "b4f19bfe07af2af24811351935a20aba1fcac811"
deps = { }

[SDL2]
url = "https://github.com/RogueMacro/SDL2-beef.git"
description = "SDL2 wrapper for Beef"

[SDL2.versions."0.1.0"]
rev = "391ce43979dd18f48f84d596ae401484df9dffdb"
deps = { }

[SDL2.versions."0.1.1"]
rev = "3c19bab83cb3ab7507e9d79bcc54f9e8dbdbc35b"
deps = { }

[TailTrace]
url = "https://github.com/RogueMacro/TailTrace.git"
description = ""

[TailTrace.versions."0.1.0"]
rev = "f3721e2e0bc64c596d24789a1ac50d7ef1771978"
deps = { }
