[dummy]
url = "https://github.com/RogueMacro/dummy"

[dummy.versions."0.1.0"]
rev = "bf02a899c6fd1b4e45de860d83141bedda278ae1"

  [dummy.versions."0.1.0".deps]
  dummy2 = "^0.1"

[dummy2]
url = "https://github.com/RogueMacro/dummy2"

[dummy2.versions."0.1.0"]
rev = "d0df5351234bb7829725119e5220f853a5ee6f32"
deps = { }
