[BuildTools]
url = "https://github.com/roguemacro/grill-buildtools"
description = "Build tools for Grill packages"

[BuildTools.versions."0.1.0"]
rev = "a403e1d34eabfba77d269b8f5a9e98941d33b3b0"
deps = { }

[BuildTools.versions."0.2.0"]
rev = "d9acea8369695b2b7b76c7d2384116d505eaf541"
deps = { }

[BuildTools.versions."0.2.1"]
rev = "a08a878b07f48445bf3eedbb61b383d66022dd1d"
deps = { }

[BuildTools.versions."0.2.2"]
rev = "bb1eb6dc87bef38b28a848cf141053a3775bdb20"
deps = { }

[BuildTools.versions."0.2.3"]
rev = "959a14ee0650decd3f5959eb19e922f7bfab8fe6"
deps = { }

[BuildTools.versions."0.2.4"]
rev = "615c803a720355614151b1bf8bab70d7cc92d0ba"
deps = { }

[GLFW]
url = "https://github.com/MineGame159/glfw-beef.git"
description = "Beef wrapper library for GLFW 3.3.4"

[GLFW.versions."3.3.4"]
rev = "b4f19bfe07af2af24811351935a20aba1fcac811"
deps = { }

[ImGui]
url = "https://github.com/roguemacro/imgui-beef-2"
description = "Dear ImGui wrapper for Beef"

[ImGui.versions."1.88.0"]
rev = "caa69bc1175567923547377590f0aebf0b01cad5"

  [ImGui.versions."1.88.0".deps]
  GLFW = "*"

[ImGui.versions."1.88.1"]
rev = "d0339553b3f85c1c157de19b5fa6c7ad57bd50bd"

  [ImGui.versions."1.88.1".deps]
  GLFW = "*"
  SDL2 = "*"

[Json]
url = "https://github.com/RogueMacro/json.git"
description = "JSON serialization format"

[Json.versions."0.1.0"]
rev = "8f3d52755eb92cd020aa85beadf86f3ac0819847"

  [Json.versions."0.1.0".deps]
  Serialize = "^0.1.0"

[OpenGL]
url = "https://github.com/RogueMacro/opengl-beef.git"
description = "OpenGL bindings"

[OpenGL.versions."3.3.0"]
rev = "3551cdc9cb576534d4e3a2efb3f3eabce565f9f7"
deps = { }

[SDL2]
url = "https://github.com/RogueMacro/SDL2-beef.git"
description = "SDL2 wrapper for Beef"

[SDL2.versions."0.1.0"]
rev = "391ce43979dd18f48f84d596ae401484df9dffdb"
deps = { }

[SDL2.versions."0.1.1"]
rev = "3c19bab83cb3ab7507e9d79bcc54f9e8dbdbc35b"
deps = { }

[Serialize]
url = "https://github.com/RogueMacro/serialize.git"
description = "De-/serialization framework"

[Serialize.versions."0.1.0"]
rev = "4765f666529cea0eba7f0754a8b6bcdff41151d1"
deps = { }

[Serialize.versions."0.1.1"]
rev = "a8e2abcc2952e2460ad01d5e1404ab6a5cdc0a4d"
deps = { }

[Serialize.versions."0.1.2"]
rev = "bca60ca9c275bd015bf14727f9cfb59c255aede5"
deps = { }

[Serialize.versions."0.1.3"]
rev = "03a9d9c6a4f1353f1ee607cba491e9ec9395d38a"
deps = { }

[Serialize.versions."0.1.4"]
rev = "b558f4e6176f6a71c7907f5e1e50f30e344ce303"
deps = { }

[TailTrace]
url = "https://github.com/RogueMacro/TailTrace.git"
description = "Logging and console style utilities"

[TailTrace.versions."0.1.0"]
rev = "f3721e2e0bc64c596d24789a1ac50d7ef1771978"
deps = { }

[TailTrace.versions."0.1.1"]
rev = "a6aed0ab84d00fed287be30fc8200390239fae2b"
deps = { }

[Toml]
url = "https://github.com/RogueMacro/toml.git"
description = "TOML serialization format"

[Toml.versions."0.1.0"]
rev = "e23bc14337ba87eaaf0e04973fe442e20cf88d1c"

  [Toml.versions."0.1.0".deps]
  Serialize = "^0.1.0"

[Toml.versions."0.1.1"]
rev = "676347fbb55103a8788e4b767450e10761f9f57e"

  [Toml.versions."0.1.1".deps]
  Serialize = "^0.1.1"

[Toml.versions."0.1.2"]
rev = "721dd64f3fdb50f76548f1236edfa741333f548e"

  [Toml.versions."0.1.2".deps]
  Serialize = "^0.1.2"

[Toml.versions."0.1.3"]
rev = "69bcce9f463418d678bc5f398223326a5eb5128d"

  [Toml.versions."0.1.3".deps]
  Serialize = "^0.1.3"

[Toml.versions."0.1.4"]
rev = "6c3bdf3e4f68804eeeb2b5930bdf3aad63703d99"

  [Toml.versions."0.1.4".deps]
  Serialize = "^0.1.4"

[dummy]
url = "https://github.com/roguemacro/dummy"
description = ""

[dummy.versions."0.1.0"]
rev = "9aef26a47ae2b5d68809d694088c5fc66ec5744e"
deps = { }

[dummy.versions."0.1.1"]
rev = "6b0d09cc8ebdc8a27bf88659dc41370395dae1a4"
deps = { }
